apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
  labels:
    type: api
    app: {{ .Values.name }}     
spec:
  ports:
    - port: {{.Values.port}}
      name: {{.Values.port_name}}
      targetPort: {{.Values.port_name}}
  selector:
    app: {{.Values.name}}
    type: {{.Values.type}}