{{- if lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "externalsecrets.external-secrets.io" }}
# Create ExternalSecret for "externalsecrets.external-secrets.io"
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: {{ .Values.name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secretmgr }}
{{- else }}
# Assume "externalsecrets.kubernetes-client.io" is installed
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - "{{ .Values.secretmgr }}"
{{- end }}
