apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  minReplicas: {{.Values.min_replicas}}
  maxReplicas: {{.Values.max_replicas}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.name}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50