apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  backendType: secretsManager
  dataFrom:
    - "{{.Values.secretmgr}}"